blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path("", views.list_of_articles, name="list_of_articles"),
	path("<int:year>/<int:month>/<int:day>/<slug:article>/", views.article_details, name="article_details"),
	path("<int:article_id>/comment/", views.comment_for_article, name="comment_for_article"),
	path("tag/<slug:tag_slug>/", views.list_of_articles, name="list_of_articles_by_tag"),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
from django.urls import reverse
from taggit.managers import TaggableManager


class ArticlePublishedManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(status=Article.Status.PUBLISHED)
		pass
	pass


class Article(models.Model):

	class Status(models.TextChoices):
		DRAFT = 'DF', 'Draft'
		PUBLISHED = 'PB', 'Published'

	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_articles')
	title = models.CharField(max_length=250)
	slug= models.SlugField(max_length=250, unique_for_date='publish')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=2,
								choices=Status.choices,
								default=Status.DRAFT
							)

	objects = models.Manager() # The default manager
	publishedArticles = ArticlePublishedManager() # The custom manager
	tags = TaggableManager()

	class Meta:
		ordering = ['-publish']
		indexes = [
			models.Index(fields=['-publish']),
		]
		pass


	def __str__(self):
		return self.title
		pass

	def get_canonical_url(self):
		return reverse('blog:article_details',
						args=[
								self.publish.year,
								self.publish.month,
								self.publish.day,
								self.slug
								]
							)
		pass

	pass


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]
    
    def __str__(self):
        return f"Comment by {self.name} on {self.article}"
        pass
    
    pass

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        pass
    
    pass

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Comment
from django.http import HttpResponse
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm
from django.views.decorators.http import require_POST
from taggit.models import Tag




def list_of_articles(request, tag_slug = None):
    articles = Article.publishedArticles.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        articles = articles.filter(tags__in=[tag])

    paginator = Paginator(articles, 3)
    page_number = request.GET.get('page', 1)
    try:
        articles = paginator.page(page_number)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        articles = paginator.page(1)

    return render(request, 'blog/list.html', {'articles': articles, 'tag': tag})


def article_details(request, year, month, day, article):
	try:
		article = get_object_or_404(Article, status=Article.Status.PUBLISHED,
					slug=article,
					publish__year=year,
					publish__month=month,
					publish__day=day
				)

		# List of active comments for this article
		comments = article.comments.filter(active=True)

		# Form for users to write comment
		form = CommentForm()

	except Article.DoesNotExist:
		raise Http404("No article found.")

	return render(request, "blog/detail.html", {
		"article": article,
		"comments": comments,
		"form": form}
	)
	pass


@require_POST
def comment_for_article(request, article_id):

    # get the article by article_id
    article = get_object_or_404(Article, id = article_id, status=Article.Status.PUBLISHED)
    comment = None
    
    # A comment form

    # form = CommentForm(data=request.Article)
    form = CommentForm(data=request.POST)

    if form.is_valid():
        # Create a Comment object before saving it to the database
        comment = form.save(commit=False)

        # Assign the article to the comment
        comment.article = article
        # Save the comment to the database
        comment.save()
        pass

    return render(request, "blog/comment.html", {"article": article, "form": form, "comment": comment})

    pass

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    
    <div class="header">
        <h2>Personal Blog</h2>
    </div>

    <div class="row">
        <div class="leftcolumn">
            <div class="card">
                {% block content %}
                {% endblock content%}
            </div>
            
        </div>
        <div class="rightcolumn">
            <div class="card">
                <h2>Blogger Website</h2>
                <p>This is my blogger website where I can write about programming and
                other stuffs.
                </p>
            </div>
            
            <div class="card">
                <h3>Latest Article</h3>
                {% block latestArticle %}
                {% endblock latestArticle %}
            </div>
            
            <div class="card">
                <h3>Most Commented Article</h3>
                {% block mostCommentedArticle %}
                {% endblock mostCommentedArticle %}
            </div>
        </div>
    </div>

    <div class="footer">
        <h5>Copyright 2023 All Right Revered </h5>
    </div> 

</body>
</html>

blog/templates/blog/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ article.get_canonical_url }}">Back to the article</a></p>
    {% else %}
        {% include "blog/comment_form.html" %}
    {% endif %}

{% endblock %}

blog/templates/blog/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:comment_for_article' article.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <h1>{{ article.title }}</h1>
    <p>
        Published {{ article.publish }} by {{ article.author }}
    </p>
    {{ article.body|linebreaks }}
    
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div>
            <p>
                Comment {{ forloop.counter }} by {{ comment.name }} on {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <div>
            <p>There are no comments.</p>
        </div>
    {% endfor %}

    {% include "blog/comment_form.html" %}
    
    <a href="/blog/">Back to the Articles</a>

{% endblock %}

blog/templates/blog/list.html
{% extends "blog/base.html" %}

{% block title %}Articles{% endblock %}

{% block content %}

    {% if tag %}
            <h2>Articles tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for article in articles %}
        <h2>
            <a href="{{ article.get_canonical_url }}">
                {{ article.title }}
            </a>
        </h2>
<p>
    Tags: 
    {% for tag in article.tags.all %}
        <a href="{% url 'blog:list_of_articles_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
        <p>
            Published {{ article.publish }} by {{ article.author }}
        </p>
        {{ article.body|truncatewords:50|linebreaks }}

    {% endfor %}
    {% include "blog/pagination.html" with page=articles %}

{% endblock %}

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="pagination-links">

        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>